/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import org.json.JSONException;
import org.json.JSONObject;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblResuCon = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Estado 3 = Otro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Estado 2 = Vendedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Estado 1 = Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtEstado.setForeground(new java.awt.Color(153, 153, 153));
        txtEstado.setText("Estado");
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 70, -1));

        lblResuCon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblResuCon.setForeground(new java.awt.Color(204, 204, 204));
        lblResuCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResuCon.setText("\"\"");
        getContentPane().add(lblResuCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 280, 20));

        txtClave.setText("1234");
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 220, -1));

        btnIngresar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser.setText("Escribe el Usuario");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Log-1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fondo_Log.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        //Importamos la libreria HTTP
        HttpClient cliente = new HttpClient(new OnHttpRequestComplete() {
            @Override
            public void onComplete(Response status) {
                if (status.isSuccess()) {
                    try {
                        //Se crea un JSONObject que crea un usuario de un "Array o diccionario" que contiene los siguientes datos:
                        JSONObject Usuarios = new JSONObject(status.getResult());
                        
                        // Obtiene el usuario y lo guarda en la variable de tipo string "usuarioBase"
                        String usuarioBase = Usuarios.getJSONObject("0").get("usuario").toString();
                        // Obtiene la clave y lo guarda en la variable de tipo string "claveBase"
                        String claveBase = Usuarios.getJSONObject("0").get("clave").toString();
                        // Obtiene el estado y lo guarda en la variable de tipo string "estadoBase"
                        String estadoBase = Usuarios.getJSONObject("0").get("estado").toString();
                        // Si los textfields tienen esos datos y las variables tambien...
                        if (txtUser.getText().toString().equals(usuarioBase)
                                && txtClave.getText().toString().equals(claveBase)
                                && txtEstado.getText().toString().equals(estadoBase)) {
                            //Verifica tambien el estado y los clasifica, 1 = admin, 2 0 Vendedor, 3 = otro...
                            if (estadoBase.contains("1")) 
                            {
                                //El estado 1 es administrador, y tiene acceso a todos los menus
                                String nombre = Usuarios.getJSONObject("0").get("nombre").toString();
                                //Da la bienvenida en un label que esta en el login
                                lblResuCon.setText("Bienvenid@: " + nombre);
                                // Crea la ventana y la pone visible.
                                Menu ventana = new Menu();
                                ventana.setVisible(true);
                                
                            }
                            else if(estadoBase.contains("2"))
                            {
                                //En el estado 2, es para el vendedor, y solo tiene acceso a la venta de productos
                                String nombre = Usuarios.getJSONObject("0").get("nombre").toString();
                                lblResuCon.setText("Bienvenid@: " + nombre);
                                Menu ventana = new Menu();
                                ventana.setVisible(true);
                                ventana.deshabilitarMenusVendedor();
                            }
                            else if(estadoBase.contains("3"))
                            {
                                String nombre = Usuarios.getJSONObject("0").get("nombre").toString();
                                lblResuCon.setText("Bienvenid@: "+ nombre);
                                Menu ventana = new Menu();
                                ventana.setVisible(true);
                                ventana.deshabilitarMenusOtro();
                            }
                        } else {

                        }

                    } catch (JSONException e) {
                    }

                }
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
        //Estas variables guardan la informacion que ingresa el usuario en los textfield
        String usuario = txtUser.getText().toString();
        String clave = txtClave.getText().toString();
        // Y se ejecutan en la API
        cliente.excecute("http://localhost/examAPI/login.php?usuario=" + usuario + "&clave=" + clave + "");
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResuCon;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
