/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author jairo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    FondoPanel fondo = new FondoPanel();

    public Menu() {

        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_reg = new javax.swing.JMenu();
        menu_AgUs = new javax.swing.JMenuItem();
        menu_Ag_Pro = new javax.swing.JMenuItem();
        menu_Act_Inv = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_vent = new javax.swing.JMenu();
        menu_Ven_Prod = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar2.png"))); // NOI18N
        menu_reg.setText("Registro");

        menu_AgUs.setText("Agregar Usuario");
        menu_AgUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AgUsActionPerformed(evt);
            }
        });
        menu_reg.add(menu_AgUs);

        menu_Ag_Pro.setText("Agregar Producto");
        menu_Ag_Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ag_ProActionPerformed(evt);
            }
        });
        menu_reg.add(menu_Ag_Pro);

        jMenuBar1.add(menu_reg);

        menu_Act_Inv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/act2.png"))); // NOI18N
        menu_Act_Inv.setText("Actualizacion ");

        jMenuItem1.setText("Actualizar Inventario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_Act_Inv.add(jMenuItem1);

        jMenuBar1.add(menu_Act_Inv);

        menu_vent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/punto2.png"))); // NOI18N
        menu_vent.setText("Ventas Producto");

        menu_Ven_Prod.setText("Venta de Productos");
        menu_Ven_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ven_ProdActionPerformed(evt);
            }
        });
        menu_vent.add(menu_Ven_Prod);

        jMenuBar1.add(menu_vent);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_Ag_ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ag_ProActionPerformed
        // Abre El submenu Agregar_Usuario
        Agregar_Producto ventana = new Agregar_Producto();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_Ag_ProActionPerformed

    private void menu_AgUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AgUsActionPerformed
        // Abre el submenu Regitrar
        Regitrar ventana = new Regitrar();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_AgUsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abre el submenu Actualizar_inventario
        Actualizar_inventario ventana = new Actualizar_inventario();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_Ven_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ven_ProdActionPerformed
        //Abre el submenu Venta, para la venta de productos
        Venta ventana = new Venta();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_Ven_ProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    //Agrega un fondo de pantalla y lo hace responcible...
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Iconos/azul.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

    //Deshabilita los menus, actualizar y registrar, para los vendedores.
    public void deshabilitarMenusVendedor(){
        menu_Act_Inv.setEnabled(false);
        menu_reg.setEnabled(false);
    }
    
    //Deshabilita los menus Registrar y ventas, para Otro.
    public void deshabilitarMenusOtro(){
        menu_reg.setEnabled(false);
        menu_vent.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu_Act_Inv;
    private javax.swing.JMenuItem menu_AgUs;
    private javax.swing.JMenuItem menu_Ag_Pro;
    private javax.swing.JMenuItem menu_Ven_Prod;
    private javax.swing.JMenu menu_reg;
    private javax.swing.JMenu menu_vent;
    // End of variables declaration//GEN-END:variables
}
